# Generated by Django 6.0.6 on 2026-06-23 23:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_purchase_user_alter_purchase_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='user',
            new_name='buyer',
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('buyer', 'book')},
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_subscription',
        ),
        migrations.AddField(
            model_name='purchase',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='ebook_file',
            field=models.FileField(blank=True, null=True, upload_to='ebooks/'),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
