# Generated by Django 6.0.6 on 2026-06-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='author_request_pending',
            field=models.BooleanField(default=False),
        ),
    ]
