# Generated by Django 5.1 on 2026-06-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_paymentconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mpesa_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='M-Pesa Number for Payments'),
        ),
    ]
