# Generated by Django 3.2 on 2026-07-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_authorrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
